[package]
name = "madoc-tauri"
version = "0.1.0"
description = "MADOC Tauri home screen"
authors = ["MADOC"]
edition = "2021"

[lib]
name = "madoc_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

