<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MADOC.Domain.Core\MADOC.Domain.Core.csproj" />
    <ProjectReference Include="..\MADOC.Printing.Html\MADOC.Printing.Html.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Content Include="Printing\Templates\**\*.*" CopyToOutputDirectory="PreserveNewest" />
		<Content Include="Printing\Styles\**\*.*" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
